model_framework: pytorch
model_file_path: ../yolov7_tk1.pt
RK_device_platform: RK3588
# RK_device_id: simulator
dataset: /home/xz/Documents/gitlab_model_zoo/rknn_model_zoo/datasets/COCO/coco_dataset_500.txt
quantize: True
pre_compile: online
core_mask: 7

graph:
  in_0:
    shape: 3,640,640
    mean_values: 0
    std_values: 255
    img_type: RGB

configs:
  quantized_dtype: asymmetric_quantized-8
  quantized_algorithm: normal
  optimization_level: 3
  batch_size: 20
